- name: Configure the new VM hostname
  hosts: 10.13.104.100
  gather_facts: yes
  become: yes
  vars:
    ansible_host: 10.13.104.100
    ansible_user: sysadmin
    ansible_ssh_pass: "123456"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - docker-role

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: espresso-instance2
